//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.nl", typeof(nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nieuw.
        /// </summary>
        public static string addButton {
            get {
                return ResourceManager.GetString("addButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voeg een departement toe.
        /// </summary>
        public static string addDepartmentHeader {
            get {
                return ResourceManager.GetString("addDepartmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voeg een nieuwe taal toe.
        /// </summary>
        public static string addLanguageHeader {
            get {
                return ResourceManager.GetString("addLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voeg een nieuwe locatie toe .
        /// </summary>
        public static string addLocationHeader {
            get {
                return ResourceManager.GetString("addLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annuleer.
        /// </summary>
        public static string cancelButtonText {
            get {
                return ResourceManager.GetString("cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bent u zeker om te verwijderen?.
        /// </summary>
        public static string confirmDeleteMessage {
            get {
                return ResourceManager.GetString("confirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijder.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijder.
        /// </summary>
        public static string deleteButton {
            get {
                return ResourceManager.GetString("deleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departement.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de departement naam is verplicht in te vullen.
        /// </summary>
        public static string departmentNameEmptyErrorMessage {
            get {
                return ResourceManager.GetString("departmentNameEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departement naam.
        /// </summary>
        public static string departmentNameLabel {
            get {
                return ResourceManager.GetString("departmentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departementen.
        /// </summary>
        public static string departments {
            get {
                return ResourceManager.GetString("departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bijwerk.
        /// </summary>
        public static string editButton {
            get {
                return ResourceManager.GetString("editButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beurzen.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        public static string internships {
            get {
                return ResourceManager.GetString("internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taal.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taal.
        /// </summary>
        public static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taal naam.
        /// </summary>
        public static string languageNameLabel {
            get {
                return ResourceManager.GetString("languageNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taal is verplicht om in te vullen.
        /// </summary>
        public static string languageNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("languageNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie stad .
        /// </summary>
        public static string locationCityLabel {
            get {
                return ResourceManager.GetString("locationCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie van de stad is verplicht .
        /// </summary>
        public static string locationCityRequiredErrorMessage {
            get {
                return ResourceManager.GetString("locationCityRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie huisnummer is verplicht .
        /// </summary>
        public static string locationHouseNumberErrorMessage {
            get {
                return ResourceManager.GetString("locationHouseNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie huisnummer.
        /// </summary>
        public static string locationHouseNumberLabel {
            get {
                return ResourceManager.GetString("locationHouseNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locaties.
        /// </summary>
        public static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie straatnaam .
        /// </summary>
        public static string locationStreetNameLabel {
            get {
                return ResourceManager.GetString("locationStreetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lcoatie straatnaam is verplicht .
        /// </summary>
        public static string locationStreetRequiredErrorMessage {
            get {
                return ResourceManager.GetString("locationStreetRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locatie postcode.
        /// </summary>
        public static string locationZipCodeLabel {
            get {
                return ResourceManager.GetString("locationZipCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lcoatie postcode is verplicht .
        /// </summary>
        public static string locationZipCodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("locationZipCodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email van manager.
        /// </summary>
        public static string managerEmail {
            get {
                return ResourceManager.GetString("managerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nieuw stageopdracht.
        /// </summary>
        public static string newInternShip {
            get {
                return ResourceManager.GetString("newInternShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opslaan.
        /// </summary>
        public static string saveButtonText {
            get {
                return ResourceManager.GetString("saveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intetum-Realdolmen Stagebundel.
        /// </summary>
        public static string TEMPLATE_TITLE {
            get {
                return ResourceManager.GetString("TEMPLATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bijwerk.
        /// </summary>
        public static string updateButtonText {
            get {
                return ResourceManager.GetString("updateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bijwerk departement.
        /// </summary>
        public static string updateDepartmentHeader {
            get {
                return ResourceManager.GetString("updateDepartmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bijwerk taal.
        /// </summary>
        public static string updateLanguageHeader {
            get {
                return ResourceManager.GetString("updateLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pas locatie aan .
        /// </summary>
        public static string updateLocationHeader {
            get {
                return ResourceManager.GetString("updateLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
